# Generated by Django 3.2.7 on 2021-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='submission',
            new_name='benchmark_submission',
        ),
        migrations.AddField(
            model_name='software',
            name='example_submission',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
