# Generated by Django 3.2.7 on 2021-10-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0002_auto_20211008_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchmarkinstance',
            old_name='efficiency',
            new_name='cpu_efficiency',
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='gpu_efficiency',
            field=models.FloatField(blank=True, default=0.0, help_text='GPU efficiency, %', null=True),
        ),
    ]
