# Generated by Django 3.2.7 on 2021-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0002_auto_20211001_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncpu', models.IntegerField()),
                ('ntasks', models.IntegerField()),
                ('ngpu', models.IntegerField()),
                ('nvlink', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='benchmarkinstance',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='nvlink',
        ),
        migrations.DeleteModel(
            name='Parameters',
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='resource',
            field=models.ManyToManyField(to='mdbench.Resource'),
        ),
    ]
