# Generated by Django 3.2.7 on 2021-10-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0003_auto_20211009_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmarkinstance',
            name='gpu_efficiency',
        ),
    ]
