# Generated by Django 3.2.7 on 2021-10-01 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0004_benchmark_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False),
        ),
    ]
