# Generated by Django 3.2.7 on 2021-10-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0004_remove_benchmarkinstance_gpu_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='cpu_efficiency',
            field=models.FloatField(help_text='Efficiency, %'),
        ),
    ]
