# Generated by Django 3.2.7 on 2021-10-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0005_alter_benchmarkinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmark',
            name='name',
            field=models.CharField(help_text='Enter a benchmark name', max_length=100),
        ),
        migrations.RemoveField(
            model_name='benchmarkinstance',
            name='cpu',
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mdbench.cpu'),
        ),
        migrations.RemoveField(
            model_name='benchmarkinstance',
            name='gpu',
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='gpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mdbench.gpu'),
        ),
        migrations.RemoveField(
            model_name='benchmarkinstance',
            name='resource',
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mdbench.resource'),
        ),
        migrations.RemoveField(
            model_name='benchmarkinstance',
            name='software',
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mdbench.software'),
        ),
    ]
