# Generated by Django 3.2.7 on 2021-10-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0006_simulationinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name_plural': '7. CPU Types'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name_plural': '8. GPU Types'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': '6. Computing Resources'},
        ),
        migrations.AlterModelOptions(
            name='simulationinput',
            options={'verbose_name_plural': '5. Simulation input files'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': '9. CC Sites'},
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mdbench.simulationinput'),
        ),
        migrations.AddField(
            model_name='serialbenchmarkinstance',
            name='input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mdbench.simulationinput'),
        ),
    ]
