# Generated by Django 3.2.7 on 2021-10-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0007_benchmarkinstance_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='efficiency',
            field=models.FloatField(help_text='%'),
        ),
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='rate',
            field=models.FloatField(help_text='ns/day'),
        ),
    ]
