# Generated by Django 3.2.7 on 2021-10-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0007_auto_20211010_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchmarkinstance',
            old_name='input',
            new_name='simulation_input',
        ),
        migrations.RenameField(
            model_name='serialbenchmarkinstance',
            old_name='input',
            new_name='simulation_input',
        ),
    ]
