# Generated by Django 3.2.7 on 2021-10-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0008_auto_20211007_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='efficiency',
            field=models.FloatField(help_text='CPU efficiency, %'),
        ),
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='rate',
            field=models.FloatField(help_text='Simulation speed, ns/day'),
        ),
    ]
