# Generated by Django 3.2.7 on 2021-10-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0008_auto_20211010_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='nnodes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
