# Generated by Django 3.2.7 on 2021-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0010_auto_20211007_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
