# Generated by Django 3.2.8 on 2021-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0010_auto_20211020_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='cpu_efficiency',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.IntegerField(help_text='Enter amount of VRAM', max_length=100),
        ),
    ]
