# Generated by Django 3.2.7 on 2021-10-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0011_alter_benchmarkinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkinstance',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mdbench.gpu'),
        ),
    ]
