# Generated by Django 3.2.8 on 2021-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0011_auto_20211104_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.IntegerField(help_text='Enter amount of VRAM'),
        ),
    ]
