# Generated by Django 3.2.8 on 2021-11-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0012_alter_gpu_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='vram',
            field=models.IntegerField(default=0, help_text='Enter amount of VRAM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.CharField(help_text='Enter a GPU model (e.g. V100)', max_length=100),
        ),
    ]
