# Generated by Django 3.2.8 on 2021-11-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0016_auto_20211123_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkinstance',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
