# Generated by Django 3.2.8 on 2021-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0017_benchmarkinstance_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkinstance',
            name='core_year',
            field=models.FloatField(default=0.0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchmarkinstance',
            name='gpu_year',
            field=models.FloatField(default=0.0, editable=False),
            preserve_default=False,
        ),
    ]
