# Generated by Django 3.2.8 on 2021-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0018_auto_20211130_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='cores_per_gpu',
            field=models.IntegerField(default=4, help_text='Enter the number of cores/GPU'),
            preserve_default=False,
        ),
    ]
