# Generated by Django 3.2.8 on 2021-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0019_gpu_cores_per_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkinstance',
            name='sbatch_script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serialbenchmarkinstance',
            name='sbatch_script',
            field=models.TextField(blank=True),
        ),
    ]
