# Generated by Django 3.2.8 on 2021-12-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdbench', '0020_auto_20211217_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='ncores',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
